Release creation script added

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,12 +22,39 @@ jobs:
   create-release:
     runs-on: ubuntu-latest
     needs: sit-build-and-deploy
-    if: startsWith(github.ref, 'refs/heads/develop')
+    if: startsWith(github.ref, 'refs/heads/develop')  || startsWith(github.ref, 'refs/heads/feature/')
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v4
-    - name: Release create
-      run: echo "Release has been completed"
+      - name: Checkout code
+        uses: actions/checkout@v4
+      - name: Release create
+        run: |
+          increment_version() {
+            local RELEASE_ORDER="$1"
+            local VERSION="$2"
+            local SEGMENT="$3"
+            local NEW_VERSION
+
+            IFS='.' read -r -a parts <<< "$VERSION"
+            if [ "$SEGMENT" == "middle" ]; then
+                ((parts[1]++))
+            elif [ "$SEGMENT" == "last" ]; then
+                ((parts[2]++))
+            else
+                echo "Invalid SEGMENT. Please use 'middle' or 'last'."
+                exit 1
+            fi
+
+            NEW_VERSION="${RELEASE_ORDER}.${parts[1]}.${parts[2]}"
+            echo "${NEW_VERSION}"
+          }
+
+          RELEASE_ORDER=1
+          LAST_RELEASE_BRANCH_NAME="1.0.0"
+          VERSION_INCREMENT="middle"
+
+          RELEASE_VERSION=$(increment_version "${RELEASE_ORDER}" "${LAST_RELEASE_BRANCH_NAME}" "${VERSION_INCREMENT}")
+          echo "New Release Version: ${RELEASE_VERSION}"
+          env
 
   uat-build-and-deploy:
     runs-on: ubuntu-latest
